# Generated by Django 4.0.4 on 2022-05-19 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_projects_assigned_users_alter_projects_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
