# Generated by Django 4.0.4 on 2022-05-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='due_date',
            field=models.CharField(max_length=50),
        ),
    ]
