# Generated by Django 4.0.4 on 2022-05-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(default='Incomplete', max_length=10),
            preserve_default=False,
        ),
    ]
