# Generated by Django 4.0.4 on 2022-05-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_date',
            field=models.CharField(max_length=50),
        ),
    ]
